import React, { useState } from 'react';
import { Bell, Database, Lock, Settings, Users, Zap } from 'lucide-react';
import { Accordion, AccordionItem } from './Accordion';
import { ComponentTokenContract, ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './AccordionDocumentation.css';

const rows:ComponentTokenContractRow[]=[
 {role:'Container surface',token:'--cvp-accordion-bg',source:'--cvp-color-surface-default',contract:'Theme-resolved section group',activation:'Base'},
 {role:'Boundary',token:'--cvp-accordion-border',source:'--cvp-color-border-default',contract:'Subtle container edge',activation:'Base'},
 {role:'Trigger text',token:'--cvp-accordion-trigger-text',source:'--cvp-color-text-secondary',contract:'4.5:1 minimum',activation:'Collapsed'},
 {role:'Expanded trigger',token:'--cvp-accordion-trigger-bg-active',source:'--cvp-color-surface-subtle',contract:'Persistent open-state cue',activation:'aria-expanded=true'},
 {role:'Focus',token:'--cvp-accordion-focus-ring',source:'--cvp-focus-border-color',contract:'Inset canonical focus boundary',activation:':focus-visible'},
 {role:'Brand icon',token:'--cvp-accordion-leading-icon-primary',source:'--cvp-color-icon-brand',contract:'Optional semantic emphasis',activation:'iconColor=primary'},
 {role:'Trigger height',token:'--cvp-accordion-trigger-height',source:'--cvp-space-900',contract:'48px minimum',activation:'All headers'},
 {role:'Content inset',token:'--cvp-accordion-content-padding-x',source:'--cvp-space-4',contract:'16px',activation:'Expanded panel'},
];

const content=(copy:string)=><div className="cvp-accordion-doc__content"><p>{copy}</p><ul><li>Clear, scannable supporting information</li><li>Content remains associated with its heading</li></ul></div>;
const baseItems:AccordionItem[]=[{id:'base',title:'Base configuration',content:content('Fundamental workspace settings that affect the overall behavior of the system.')},{id:'query',title:'Content query',content:content('Retrieval rules, source selection, and query optimization settings.')},{id:'delivery',title:'Delivery',content:content('Publishing destinations and availability configuration.')}];

export function AccordionDocumentation(){
 const[expanded,setExpanded]=useState<string[]>(['query']);
 return <main className="cvp-input-doc cvp-accordion-doc">
  <header className="cvp-input-doc__hero"><div><span>Navigation 04 · Standardized</span><h1>Accordion</h1></div><div><p>A vertically stacked disclosure pattern for progressively revealing related settings and supporting information.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
  <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>Heading, trigger, disclosure icon, and region form one predictable relationship.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live"><Accordion items={baseItems} expandedItems={expanded} onExpandedChange={setExpanded}/><p className="cvp-accordion-doc__result">Expanded: <strong>{expanded.join(', ')||'None'}</strong></p></div><ol><li><b>1</b><span><strong>Heading</strong> Preserves document hierarchy through a configurable level.</span></li><li><b>2</b><span><strong>Trigger</strong> Owns expanded state and panel relationship.</span></li><li><b>3</b><span><strong>Chevron</strong> Reinforces state without replacing its accessible name.</span></li><li><b>4</b><span><strong>Region</strong> Is labelled by the controlling trigger.</span></li></ol></div></section>
  <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Variants and states</h2><p>Expansion model, icon treatment, and availability are explicit properties.</p></div></header><div className="cvp-accordion-doc__variants"><article><span>Single expansion</span><Accordion items={baseItems} defaultExpanded={['base']}/></article><article><span>Multiple expansion</span><Accordion type="multiple" defaultExpanded={['general','security']} items={[{id:'general',title:'General settings',icon:<Settings/>,content:content('Language, timezone, and display preferences.')},{id:'security',title:'Security',icon:<Lock/>,content:content('Authentication and session management.')},{id:'alerts',title:'Notifications',icon:<Bell/>,content:content('Delivery channels and alert frequency.')} ]}/></article><article><span>Primary icons</span><Accordion type="multiple" items={[{id:'performance',title:'Performance',icon:<Zap/>,iconColor:'primary',content:content('Caching and background processing.')},{id:'database',title:'Database',icon:<Database/>,iconColor:'primary',content:content('Connection, schema, and recovery configuration.')},{id:'users',title:'Users',icon:<Users/>,iconColor:'primary',content:content('Membership and permission management.')} ]}/></article><article><span>Disabled states</span><Accordion items={[{id:'available',title:'Available section',content:content('This section can be expanded.')},{id:'locked',title:'Unavailable section',disabled:true,content:content('This section cannot be expanded.')} ]}/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Theme parity</h2><p>Surface, dividers, hierarchy, focus, icons, and disabled states resolve semantically.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><Accordion items={baseItems.slice(0,2)} defaultExpanded={['base']}/></article><article data-theme="light"><span>Light</span><Accordion items={baseItems.slice(0,2)} defaultExpanded={['base']}/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Token contract</h2><p>Accordion owns registered Tier 3 surface, interaction, hierarchy, spacing, typography, and motion roles.</p></div></header><ComponentTokenContract label="Accordion token contract" rows={rows}/></section>
  <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>05</b><div><h2>Accessibility contract</h2></div></header><ul><li>Each trigger is wrapped in a configurable semantic heading.</li><li>Unique IDs connect every trigger and region.</li><li>Native buttons provide Enter and Space activation.</li><li>Arrow Up/Down, Home, and End move between enabled headings.</li><li>Disabled items retain meaning and are skipped.</li><li>Collapsed content is removed from the focus order.</li></ul></article><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Usage decisions</h2></div></header><ul><li>Use for optional supporting detail, not required sequential steps.</li><li>Prefer single expansion when open sections are lengthy.</li><li>Use multiple expansion for comparison and settings workflows.</li><li>Keep headings concise and content self-contained.</li><li>Do not nest accordions deeply.</li><li>Choose the heading level to match the surrounding page.</li></ul></article></section>
  <footer className="cvp-input-doc__footer"><span>CVP navigation family</span><p>Disclosure · Single/multiple expansion · Heading hierarchy · Roving focus</p></footer>
 </main>;
}
