import React,{useEffect,useId,useMemo,useRef,useState}from'react';
import{ChevronLeft,ChevronRight,Clock3,X}from'lucide-react';
import'./DatePicker.css';

export type DatePickerMode='single'|'range';
export interface DatePickerValue{start:Date|null;end:Date|null;startTime?:string;endTime?:string}
export interface DatePickerProps{mode?:DatePickerMode;value?:DatePickerValue;defaultValue?:DatePickerValue;onChange?:(value:DatePickerValue)=>void;label?:string;showTime?:boolean;disabled?:boolean;minDate?:Date;maxDate?:Date;className?:string}

const same=(a:Date|null,b:Date|null)=>Boolean(a&&b&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate());
const startOfDay=(date:Date)=>new Date(date.getFullYear(),date.getMonth(),date.getDate());
const dateLabel=(date:Date)=>date.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});

function TimeSelector({label,value,onChange,disabled}:{label:string;value:string;onChange:(value:string)=>void;disabled:boolean}){const[open,setOpen]=useState(false);const uid=useId().replace(/:/g,'');const dialogId=`time-dialog-${uid}`;const rootRef=useRef<HTMLDivElement>(null);const[hour='00',minute='00']=value.split(':');useEffect(()=>{const outside=(event:MouseEvent)=>{if(rootRef.current&&!rootRef.current.contains(event.target as Node))setOpen(false)};document.addEventListener('mousedown',outside);return()=>document.removeEventListener('mousedown',outside)},[]);return <div className="cvp-date-picker__time-field" ref={rootRef}><span>{label}</span><button type="button" className="cvp-date-picker__time-trigger" onClick={()=>setOpen(current=>!current)} disabled={disabled} aria-haspopup="dialog" aria-expanded={open} aria-controls={dialogId}><Clock3 aria-hidden="true"/><span>{value}</span></button>{open&&<div className="cvp-date-picker__time-dialog" id={dialogId} role="dialog" aria-label={`Choose ${label.toLocaleLowerCase()}`} onKeyDown={event=>{if(event.key==='Escape')setOpen(false)}}><header><div><b>{label}</b><span>{value}</span></div><button type="button" onClick={()=>setOpen(false)} aria-label={`Close ${label.toLocaleLowerCase()} selector`}><X aria-hidden="true"/></button></header><div className="cvp-date-picker__time-columns"><section><h4>Hour</h4><div className="cvp-date-picker__time-options">{Array.from({length:24},(_,index)=>String(index).padStart(2,'0')).map(option=><button type="button" key={option} aria-pressed={hour===option} onClick={()=>onChange(`${option}:${minute}`)}>{option}</button>)}</div></section><section><h4>Minute</h4><div className="cvp-date-picker__time-options cvp-date-picker__time-options--minutes">{['00','15','30','45'].map(option=><button type="button" key={option} aria-pressed={minute===option} onClick={()=>onChange(`${hour}:${option}`)}>{option}</button>)}</div></section></div><footer><button type="button" onClick={()=>setOpen(false)}>Done</button></footer></div>}</div>}

export function DatePicker({mode='single',value,defaultValue={start:null,end:null,startTime:'00:00',endTime:'00:00'},onChange,label='Choose date',showTime=false,disabled=false,minDate,maxDate,className=''}:DatePickerProps){
 const[internal,setInternal]=useState(defaultValue);const[month,setMonth]=useState(()=>startOfDay(value?.start??defaultValue.start??new Date()));const current=value??internal;
 const commit=(next:DatePickerValue)=>{if(value===undefined)setInternal(next);onChange?.(next)};
 const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),offset=(first.getDay()+6)%7,count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return[...Array(offset).fill(null),...Array.from({length:count},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i+1))]},[month]);
 const choose=(date:Date)=>{if(mode==='single'){commit({...current,start:date,end:null});return}if(!current.start||current.end){commit({...current,start:date,end:null})}else if(date<current.start){commit({...current,start:date,end:current.start})}else{commit({...current,end:date})}};
 const inRange=(date:Date)=>Boolean(current.start&&current.end&&date>current.start&&date<current.end);
 const unavailable=(date:Date)=>disabled||Boolean(minDate&&startOfDay(date)<startOfDay(minDate))||Boolean(maxDate&&startOfDay(date)>startOfDay(maxDate));
 return <section className={['cvp-date-picker',className].filter(Boolean).join(' ')} aria-label={label} data-disabled={disabled||undefined}>
  <header className="cvp-date-picker__header"><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} aria-label="Previous month" disabled={disabled}><ChevronLeft aria-hidden="true"/></button><h3 aria-live="polite">{month.toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h3><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} aria-label="Next month" disabled={disabled}><ChevronRight aria-hidden="true"/></button></header>
  <div className="cvp-date-picker__weekdays" aria-hidden="true">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=><span key={day}>{day}</span>)}</div>
  <div className="cvp-date-picker__grid" role="group" aria-label={`${month.toLocaleDateString('en-GB',{month:'long',year:'numeric'})} calendar`}>{days.map((date,index)=>date?<button key={date.toISOString()} type="button" aria-label={dateLabel(date)} aria-pressed={same(date,current.start)||same(date,current.end)} disabled={unavailable(date)} data-selected={(same(date,current.start)||same(date,current.end))||undefined} data-in-range={inRange(date)||undefined} data-today={same(date,new Date())||undefined} onClick={()=>choose(date)}>{date.getDate()}</button>:<span key={`blank-${index}`} aria-hidden="true"/>)}</div>
  {showTime&&<div className="cvp-date-picker__time"><TimeSelector label={mode==='range'?'Start time':'Time'} value={current.startTime??'00:00'} disabled={disabled} onChange={startTime=>commit({...current,startTime})}/>{mode==='range'&&<TimeSelector label="End time" value={current.endTime??'00:00'} disabled={disabled} onChange={endTime=>commit({...current,endTime})}/>}</div>}
  <footer className="cvp-date-picker__summary"><span>{current.start?dateLabel(current.start):'No date selected'}</span>{mode==='range'&&<span>{current.end?`to ${dateLabel(current.end)}`:'Choose an end date'}</span>}</footer>
 </section>;
}
