import React,{useState}from'react';
import{DatePicker,DatePickerValue}from'./DatePicker';
import{ComponentTokenContract,ComponentTokenContractRow}from'./ComponentTokenContract';
import'./TextInputDocumentation.css';
import'./DatePickerDocumentation.css';

const mayRange={start:new Date(2026,4,7),end:new Date(2026,4,14),startTime:'09:00',endTime:'17:30'};
const rows:ComponentTokenContractRow[]=[{role:'Calendar surface',token:'--cvp-date-picker-bg',source:'--cvp-color-surface-overlay',contract:'Overlay surface',activation:'Panel'},{role:'Boundary',token:'--cvp-date-picker-border',source:'--cvp-color-border-strong',contract:'Subtle container edge',activation:'Panel'},{role:'Selected day',token:'--cvp-date-picker-day-selected-bg',source:'--cvp-color-brand-default',contract:'Theme-safe selection',activation:'Selected'},{role:'Selected text',token:'--cvp-date-picker-day-selected-text',source:'--cvp-color-text-on-brand',contract:'4.5:1 minimum',activation:'Selected'},{role:'Range',token:'--cvp-date-picker-range-bg',source:'--cvp-color-menu-item-active-bg',contract:'Connected range',activation:'Between endpoints'},{role:'Today',token:'--cvp-date-picker-today-border',source:'--cvp-focus-border-color',contract:'Current-day marker',activation:'Today'},{role:'Time dialog',token:'--cvp-date-picker-time-dialog-bg',source:'--cvp-color-surface-overlay',contract:'Theme-resolved overlay',activation:'Time selector open'},{role:'Time selection',token:'--cvp-date-picker-time-selected-bg',source:'--cvp-color-brand-default',contract:'Selected hour/minute',activation:'aria-pressed=true'},{role:'Focus',token:'--cvp-date-picker-focus-ring',source:'--cvp-border-focus-ring',contract:'Canonical ring',activation:':focus-visible'},{role:'Day target',token:'--cvp-date-picker-day-size',source:'--cvp-space-8',contract:'32px in dense calendar',activation:'Day grid'}];

export function DatePickerDocumentation(){const[single,setSingle]=useState<DatePickerValue>({start:new Date(2026,4,12),end:null});const[range,setRange]=useState<DatePickerValue>(mayRange);return <main className="cvp-input-doc cvp-date-doc">
 <header className="cvp-input-doc__hero"><div><span>Component 15 · Extracted</span><h1>Date Picker</h1></div><div><p>A standalone calendar for single dates, ranges, optional times, bounded dates, and explicit selection review.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
 <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Single-date selection</h2><p>Date Picker now has its own lifecycle and no longer lives inside Filter documentation.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live"><DatePicker label="Publication date" value={single} onChange={setSingle}/></div><ol><li><b>1</b><span><strong>Month navigation</strong> Native buttons announce their direction.</span></li><li><b>2</b><span><strong>Calendar group</strong> Day buttons expose their full date and selected state.</span></li><li><b>3</b><span><strong>Selection summary</strong> Confirms the chosen date in readable form.</span></li></ol></div></section>
 <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Range and time modes</h2><p>Range selection establishes a start, then an end; an earlier second choice safely reorders the interval.</p></div></header><div className="cvp-date-doc__variants"><article><span>Date range</span><DatePicker mode="range" value={range} onChange={setRange} label="Reporting period"/></article><article><span>Date and time range</span><DatePicker mode="range" value={range} onChange={setRange} label="Scheduled window" showTime/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Boundary states</h2><p>Unavailable dates remain native disabled buttons; disabled calendars preserve context without accepting input.</p></div></header><div className="cvp-date-doc__variants"><article><span>Minimum / maximum</span><DatePicker label="Booking date" defaultValue={{start:new Date(2026,4,12),end:null}} minDate={new Date(2026,4,5)} maxDate={new Date(2026,4,22)}/></article><article><span>Disabled</span><DatePicker label="Archived date" defaultValue={{start:new Date(2026,4,12),end:null}} disabled/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Theme parity</h2><p>Calendar surface, selected endpoints, range fill, today, focus, and muted metadata resolve locally.</p></div></header><div className="cvp-input-doc__themes cvp-date-doc__themes"><article data-theme="dark"><span>Dark</span><DatePicker label="Dark calendar" defaultValue={mayRange} mode="range"/></article><article data-theme="light"><span>Light</span><DatePicker label="Light calendar" defaultValue={mayRange} mode="range"/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>05</b><div><h2>Token contract</h2><p>Date Picker owns a registered calendar contract and composes canonical input tokens for time fields.</p></div></header><ComponentTokenContract label="Date Picker token contract" rows={rows}/></section>
 <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>DOM contract</h2></div></header><ul><li>The calendar region has a product-specific accessible label.</li><li>Every day remains a native button named with weekday, date, month, and year.</li><li>Selected endpoints use <code>aria-pressed</code>; unavailable dates use native disabled.</li><li>Month changes are announced through the live heading.</li><li>Time values use native labelled time inputs.</li></ul></article><article className="cvp-input-doc__panel"><header><b>07</b><div><h2>Usage decisions</h2></div></header><ul><li>Use native date input when a calendar view adds no value.</li><li>Use range mode only when both endpoints form one value.</li><li>Show time only when scheduling precision is required.</li><li>Never encode availability using color alone.</li><li>Filter may launch Date Picker but must not duplicate it.</li></ul></article></section>
 <footer className="cvp-input-doc__footer"><span>CVP date-picker reference</span><p>Single · Range · Time · Bounds · Dual-theme calendar</p></footer>
 </main>}
