import React,{useState}from'react';
import{Calendar,Database,Tag,Type}from'lucide-react';
import{ActiveFilter,Filter,FilterOption}from'./Filter';
import{ComponentTokenContract,ComponentTokenContractRow}from'./ComponentTokenContract';
import'./TextInputDocumentation.css';
import'./FilterDocumentation.css';

const options:FilterOption[]=[{id:'title',label:'Title',icon:<Type/>,type:'text'},{id:'source',label:'Source',icon:<Database/>,type:'select',options:[{value:'editorial',label:'Editorial'},{value:'partner',label:'Partner'},{value:'archive',label:'Archive'}]},{id:'tag',label:'Tag',icon:<Tag/>,type:'multiselect',options:[{value:'recommended',label:'Recommended'},{value:'featured',label:'Featured'}]},{id:'published',label:'Published',icon:<Calendar/>,type:'date'},{id:'active',label:'Active only',type:'boolean'}];
const initial:ActiveFilter[]=[{id:'source',label:'Source',value:'editorial',displayValue:'Editorial'}];
const rows:ComponentTokenContractRow[]=[{role:'Bar surface',token:'--cvp-filter-bg',source:'--cvp-input-bg',contract:'Shared input surface',activation:'Base'},{role:'Bar border',token:'--cvp-filter-border',source:'--cvp-input-border',contract:'Subtle field boundary',activation:'Base'},{role:'Focus',token:'--cvp-filter-focus-ring',source:'--cvp-input-focus-ring',contract:'Canonical visible ring',activation:':focus-within / open'},{role:'Clause surface',token:'--cvp-filter-chip-bg',source:'--cvp-color-surface-active',contract:'Theme-resolved clause',activation:'Active filter'},{role:'Popup',token:'--cvp-filter-menu-bg',source:'--cvp-menu-bg',contract:'Overlay surface',activation:'Open'},{role:'Popup shadow',token:'--cvp-filter-menu-shadow',source:'--cvp-menu-shadow',contract:'Elevation 2',activation:'Open'},{role:'Option hover',token:'--cvp-filter-option-hover',source:'--cvp-menu-item-bg-hover',contract:'Menu feedback',activation:':hover'},{role:'Height',token:'--cvp-filter-height',source:'--cvp-input-height',contract:'40px minimum; wraps',activation:'Bar'}];

export function FilterDocumentation(){const[filters,setFilters]=useState(initial);return <main className="cvp-input-doc cvp-filter-doc">
 <header className="cvp-input-doc__hero"><div><span>Component 14 · Standardized</span><h1>Filter</h1></div><div><p>A clause composer for finding a filter field, choosing its value, and reviewing or removing active constraints.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
 <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>Filter owns query clauses. The full calendar has moved to the standalone Date Picker page.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live"><Filter label="Content filters" options={options} activeFilters={filters} onChange={setFilters}/></div><ol><li><b>1</b><span><strong>Active clauses</strong> Field and value remain visible with a named removal action.</span></li><li><b>2</b><span><strong>Add-filter trigger</strong> Opens the searchable field menu.</span></li><li><b>3</b><span><strong>Value editor</strong> Text, enumerated, boolean, and relative-date values stay lightweight.</span></li></ol></div></section>
 <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Complete states</h2><p>The bar wraps naturally as clauses accumulate and retains the shared form focus language.</p></div></header><div className="cvp-filter-doc__states"><article><span>Empty</span><Filter options={options}/></article><article><span>Hover</span><Filter options={options} previewState="hover"/></article><article><span>Focus</span><Filter options={options} previewState="focus"/></article><article><span>Populated</span><Filter options={options} activeFilters={initial}/></article><article><span>Multiple clauses</span><Filter options={options} activeFilters={[...initial,{id:'tag',label:'Tag',value:'recommended',displayValue:'Recommended'}]}/></article><article><span>Disabled</span><Filter options={options} activeFilters={initial} disabled/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Trigger variants</h2><p>Use the bar when active clauses must remain visible; use the standardized Icon Button in compact toolbars and expose the active count as a badge.</p></div></header><div className="cvp-filter-doc__triggers"><article><span>Clause bar</span><Filter label="Content filters" options={options} activeFilters={initial}/></article><article><span>Icon button</span><Filter label="Filter rails" options={options} activeFilters={initial} triggerVariant="icon"/></article><article><span>Icon button · empty</span><Filter label="Filter rails" options={options} triggerVariant="icon"/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Supported value paths</h2><p>Calendar selection is a separate component; Filter may reference relative date presets or launch a product-owned Date Picker flow.</p></div></header><div className="cvp-filter-doc__paths"><article><b>Text</b><p>Enter a free-text match and apply.</p></article><article><b>Select / multi-value</b><p>Choose a governed value from the submenu.</p></article><article><b>Boolean</b><p>Adds immediately as an enabled clause.</p></article><article><b>Date</b><p>Uses relative presets; custom dates belong to Date Picker.</p></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>05</b><div><h2>Theme parity</h2><p>Bar, clauses, menu, search, focus and interactive feedback resolve through semantic roles.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><Filter options={options} activeFilters={initial}/></article><article data-theme="light"><span>Light</span><Filter options={options} activeFilters={initial}/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>06</b><div><h2>Token contract</h2><p>Filter extends the canonical input and menu contracts with registered clause roles.</p></div></header><ComponentTokenContract label="Filter token contract" rows={rows}/></section>
 <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>07</b><div><h2>DOM contract</h2></div></header><ul><li>The trigger is a native button with expanded, controls, and popup semantics.</li><li>The popup is labelled and field choices use menu items.</li><li>Each clause-removal action includes the field name.</li><li>Search and text value editors use native labelled inputs.</li><li>Escape closes the menu and outside click dismisses it.</li></ul></article><article className="cvp-input-doc__panel"><header><b>08</b><div><h2>Usage decisions</h2></div></header><ul><li>Replace an existing field clause rather than silently duplicate it.</li><li>Use Filter Group for explicit AND/OR composition.</li><li>Keep arbitrary calendar logic in Date Picker.</li><li>Use human-readable display values while preserving machine values.</li><li>Do not hide active constraints behind the menu.</li></ul></article></section>
 <footer className="cvp-input-doc__footer"><span>CVP filter reference</span><p>Clause composition · Search · Value paths · Removable constraints</p></footer>
 </main>}
