import React, { useState } from 'react';
import { HeaderNavigation } from './HeaderNavigation';
import { sampleAccounts, sampleTeams } from './HeaderNavigationSampleData';
import { ComponentTokenContract, ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './HeaderNavigationDocumentation.css';

const rows:ComponentTokenContractRow[]=[
  {role:'Header surface',token:'--cvp-header-bg',source:'--cvp-color-nav-bg',contract:'Theme-resolved global navigation',activation:'Base'},
  {role:'Boundary',token:'--cvp-header-border-bottom',source:'--cvp-color-border-subtle',contract:'Subtle page separation',activation:'Base'},
  {role:'Control text',token:'--cvp-header-control-text',source:'--cvp-color-text-primary',contract:'Current selection',activation:'Selectors'},
  {role:'Interaction',token:'--cvp-header-btn-bg-hover',source:'--cvp-color-surface-hover',contract:'Shared subtle feedback',activation:':hover / expanded'},
  {role:'Focus',token:'--cvp-header-focus-ring',source:'--cvp-border-focus-ring',contract:'Canonical visible ring',activation:':focus-visible'},
  {role:'Avatar',token:'--cvp-header-avatar-bg',source:'--cvp-color-brand-default',contract:'Theme-safe identity marker',activation:'User trigger'},
  {role:'Menu surface',token:'--cvp-header-menu-bg',source:'--cvp-menu-bg',contract:'Shared menu contract',activation:'Menu open'},
  {role:'Header height',token:'--cvp-header-height',source:'--cvp-space-900',contract:'48px',activation:'All layouts'},
];

export function HeaderNavigationDocumentation(){
 const[account,setAccount]=useState('console-vms'),[team,setTeam]=useState('content-team'),[status,setStatus]=useState('Ready');
 const header=<HeaderNavigation variant="static" accounts={sampleAccounts} selectedAccountId={account} onAccountChange={id=>{setAccount(id);setStatus(`Account: ${sampleAccounts.find(item=>item.id===id)?.name}`)}} teams={sampleTeams} selectedTeamId={team} onTeamChange={id=>{setTeam(id);setStatus(`Team: ${sampleTeams.find(item=>item.id===id)?.name}`)}} onHelpClick={()=>setStatus('Help requested')} onAccountDetails={()=>setStatus('Account details requested')} onThemeSwitch={()=>setStatus('Theme switch requested')} onLogOut={()=>setStatus('Log out requested')}/>;
 return <main className="cvp-input-doc cvp-header-doc">
  <header className="cvp-input-doc__hero"><div><span>Navigation 02 · Standardized</span><h1>Header Navigation</h1></div><div><p>The persistent CVP application bar for product identity, workspace context, assistance, and account actions.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
  <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>High-frequency global actions remain compact while account and team context stay visible.</p></div></header><div className="cvp-header-doc__anatomy"><div className="cvp-header-doc__preview">{header}<div><span>Interaction result</span><strong>{status}</strong></div></div><ol><li><b>1</b><span><strong>Product identity</strong> Links to the application home.</span></li><li><b>2</b><span><strong>Account selector</strong> Changes the active tenant or workspace.</span></li><li><b>3</b><span><strong>Global help</strong> Composes the canonical Icon Button.</span></li><li><b>4</b><span><strong>Team selector</strong> Changes operational context when available.</span></li><li><b>5</b><span><strong>User menu</strong> Groups identity, preferences, and session actions.</span></li></ol></div></section>
  <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Responsive contract</h2><p>Context is progressively condensed without hiding the primary account or user access.</p></div></header><div className="cvp-header-doc__widths"><article><span>Desktop · full context</span><HeaderNavigation variant="static" accounts={sampleAccounts} teams={sampleTeams}/></article><article data-size="tablet"><span>Tablet · condensed labels</span><HeaderNavigation variant="static" accounts={sampleAccounts} teams={sampleTeams}/></article><article data-size="mobile"><span>Mobile · account and profile</span><HeaderNavigation variant="static" accounts={sampleAccounts} teams={sampleTeams}/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Theme parity</h2><p>Navigation, menus, avatar, dividers, and focus indicators all resolve semantically.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><HeaderNavigation variant="static" brandName="Rail Manager"/></article><article data-theme="light"><span>Light</span><HeaderNavigation variant="static" brandName="Rail Manager"/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Token contract</h2><p>Header Navigation owns registered Tier 3 roles and composes canonical icon-button and menu contracts.</p></div></header><ComponentTokenContract label="Header Navigation token contract" rows={rows}/></section>
  <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>05</b><div><h2>Accessibility contract</h2></div></header><ul><li>Uses a semantic application header.</li><li>Every icon-only control has an accessible name.</li><li>Selectors expose menu ownership and expanded state.</li><li>Selected account and team options use <code>menuitemradio</code>.</li><li>Menus support Arrow keys, Home, End, Escape, and outside click.</li><li>Danger remains visible through text, not color alone.</li></ul></article><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Usage decisions</h2></div></header><ul><li>Keep global actions stable across product pages.</li><li>Show selectors only when multiple contexts exist.</li><li>Do not place page-specific actions in the header.</li><li>Keep sign-out separated from preference actions.</li><li>Use <code>fixed</code> in production and <code>static</code> in composed previews.</li></ul></article></section>
  <footer className="cvp-input-doc__footer"><span>CVP navigation family</span><p>Global context · Shared controls · Responsive hierarchy · Keyboard menus</p></footer>
 </main>;
}
