import React from 'react';
import { Filter, Image, MoreVertical, Search, Settings, Trash2 } from 'lucide-react';
import { IconButton } from './IconButton';
import { ComponentTokenContract, ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './PrimaryButtonDocumentation.css';
import './IconButtonDocumentation.css';

const tokenRows:ComponentTokenContractRow[]=[
 {role:'Icon',token:'--cvp-button-icon-color',source:'--cvp-color-icon-subtle',contract:'Theme-resolved',activation:'Base'},
 {role:'Hover icon',token:'--cvp-button-icon-color-hover',source:'--cvp-color-text-primary',contract:'Higher emphasis',activation:':hover'},
 {role:'Hover surface',token:'--cvp-button-icon-bg-hover',source:'--cvp-color-surface-hover',contract:'Subtle surface',activation:':hover'},
 {role:'Pressed',token:'--cvp-button-icon-bg-active',source:'--cvp-color-interactive-overlay-medium',contract:'Overlay + 1px offset',activation:':active'},
 {role:'Focus',token:'--cvp-button-icon-focus-ring',source:'--cvp-border-focus-ring',contract:'Border + outer halo',activation:':focus-visible'},
 {role:'Disabled icon',token:'--cvp-button-icon-color-disabled',source:'--cvp-color-text-disabled',contract:'Theme resolved',activation:':disabled'},
 {role:'Small target',token:'--cvp-button-icon-size-sm',source:'--cvp-space-6',contract:'24px',activation:'size="small"'},
 {role:'Default target',token:'--cvp-button-icon-size-md',source:'--cvp-space-8',contract:'32px',activation:'size="medium"'},
 {role:'Large target',token:'--cvp-button-icon-size-lg',source:'--cvp-space-800',contract:'40px',activation:'size="large"'},
 {role:'Glyph',token:'--cvp-button-icon-glyph-size',source:'--cvp-space-4',contract:'16px',activation:'All sizes'},
 {role:'Danger',token:'--cvp-button-icon-danger-color',source:'--cvp-color-icon-danger',contract:'Destructive intent',activation:'variant="danger"'},
 {role:'Gallery',token:'--cvp-button-icon-gallery-bg / --cvp-button-icon-gallery-bg-hover',source:'--cvp-color-gallery-overlay / --cvp-color-gallery-overlay-hover',contract:'Contrast-safe media control surface',activation:'variant="rail-gallery"'},
];
const states=[['Default',undefined,false,false],['Hover','hover',false,false],['Pressed','active',false,false],['Focus','focus',false,false],['Loading',undefined,false,true],['Disabled',undefined,true,false]] as const;

export function IconButtonDocumentation(){return <main className="cvp-input-doc cvp-button-doc cvp-icon-doc">
 <header className="cvp-input-doc__hero"><div><span>Component 07 · Standardized</span><h1>Icon Button</h1></div><div><p>A compact, single-action control for universally recognizable icons, with an explicit accessible name required by its API.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
 <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>A square native button target containing one decorative glyph and a programmatic action name.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live cvp-button-doc__live"><IconButton aria-label="Settings"><Settings/></IconButton></div><ol><li><b>1</b><span><strong>Target</strong> Native <code>button</code> provides activation and disabled behavior.</span></li><li><b>2</b><span><strong>Glyph</strong> Decorative and hidden from the accessibility tree.</span></li><li><b>3</b><span><strong>Name</strong> Required <code>aria-label</code> describes the action, not the icon.</span></li></ol></div></section>
 <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Complete state model</h2><p>All states preserve target geometry; loading swaps the glyph for a tokenized spinner.</p></div></header><div className="cvp-button-doc__states cvp-icon-doc__states">{states.map(([label,state,disabled,loading])=><article key={label}><span>{label}</span><IconButton aria-label="Settings" loading={loading} loadingLabel="Loading settings" disabled={disabled} data-preview-state={state}><Settings/></IconButton></article>)}</div></section>
 <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Sizes and variants</h2><p>Medium is the general default; small is limited to dense toolbars with adequate spacing.</p></div></header><div className="cvp-icon-doc__matrix"><article><span>Small · 24px</span><IconButton size="small" aria-label="Filter"><Filter/></IconButton></article><article><span>Medium · 32px</span><IconButton aria-label="Search"><Search/></IconButton></article><article><span>Large · 40px</span><IconButton size="large" aria-label="Settings"><Settings/></IconButton></article><article><span>Outline</span><IconButton variant="outline" aria-label="More options"><MoreVertical/></IconButton></article><article><span>Ghost</span><IconButton variant="ghost" aria-label="Filter"><Filter/></IconButton></article><article><span>Danger</span><IconButton variant="danger" aria-label="Delete"><Trash2/></IconButton></article><article className="cvp-icon-doc__gallery"><span>Rail gallery</span><IconButton variant="rail-gallery" aria-label="Open gallery"><Image/></IconButton></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Theme parity</h2><p>Icon, state surface, border, danger, and focus roles resolve independently in each theme.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><IconButton variant="outline" aria-label="Settings"><Settings/></IconButton></article><article data-theme="light"><span>Light</span><IconButton variant="outline" aria-label="Settings"><Settings/></IconButton></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>05</b><div><h2>Token contract</h2><p>Every visual decision resolves through the registered Tier 3 icon-button contract.</p></div></header><ComponentTokenContract label="Icon Button token contract" rows={tokenRows}/></section>
 <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Accessibility contract</h2></div></header><ul><li>An explicit action-oriented <code>aria-label</code> is mandatory.</li><li>The child glyph is decorative and receives <code>aria-hidden</code>.</li><li>Use 32px or 40px targets where layout permits.</li><li>Separate 24px targets sufficiently to avoid adjacent-target errors.</li><li>Loading announces busy state and prevents repeat activation.</li></ul></article><article className="cvp-input-doc__panel"><header><b>07</b><div><h2>Usage decisions</h2></div></header><ul><li>Use only for familiar, unambiguous actions.</li><li>Use Icon Button with Text when meaning needs a visible label.</li><li>Use Danger only for destructive intent.</li><li>Use Rail Gallery only over media or gallery surfaces.</li><li>Do not place competing icon variants in one cluster.</li></ul></article></section>
 <footer className="cvp-input-doc__footer"><span>CVP button family reference</span><p>Required name · Canonical tokens · Targets · Loading · Themes</p></footer>
</main>}
