import React from 'react';
import { Copy, Edit, GripVertical, Pin, Settings, Trash2, X } from 'lucide-react';
import { IconSmallButton } from './IconSmallButton';
import { IconButton } from './IconButton';
import { ComponentTokenContract, ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './PrimaryButtonDocumentation.css';
import './IconButtonDocumentation.css';

const tokenRows:ComponentTokenContractRow[]=[
 {role:'Target',token:'--cvp-button-icon-size-sm',source:'--cvp-space-6',contract:'24px square',activation:'Always'},
 {role:'Glyph',token:'--cvp-button-icon-glyph-size',source:'--cvp-space-4',contract:'16px maximum',activation:'Always'},
 {role:'Icon',token:'--cvp-button-icon-color',source:'--cvp-color-icon-subtle',contract:'Theme-resolved',activation:'Base'},
 {role:'Hover surface',token:'--cvp-button-icon-bg-hover',source:'--cvp-color-surface-hover',contract:'Subtle surface',activation:':hover'},
 {role:'Pressed',token:'--cvp-button-icon-bg-active',source:'--cvp-color-interactive-overlay-medium',contract:'Overlay + 1px offset',activation:':active'},
 {role:'Focus',token:'--cvp-button-icon-focus-ring',source:'--cvp-border-focus-ring',contract:'Border + outer halo',activation:':focus-visible'},
 {role:'Danger',token:'--cvp-button-icon-danger-color',source:'--cvp-color-icon-danger',contract:'Destructive intent',activation:'variant="danger"'},
 {role:'Remove surface',token:'--cvp-button-icon-remove-bg',source:'--cvp-color-gallery-overlay',contract:'Circular media overlay',activation:'variant="remove"'},
 {role:'Remove hover',token:'--cvp-button-icon-remove-bg-hover',source:'--cvp-color-state-danger-bg',contract:'Theme-safe danger pairing',activation:':hover'},
 {role:'Loading',token:'--cvp-button-icon-spinner-size',source:'--cvp-space-4',contract:'16px / 2px stroke',activation:'loading={true}'},
];
const states=[['Default',undefined,false,false],['Hover','hover',false,false],['Pressed','active',false,false],['Focus','focus',false,false],['Loading',undefined,false,true],['Disabled',undefined,true,false]] as const;

export function IconSmallButtonDocumentation(){return <main className="cvp-input-doc cvp-button-doc cvp-icon-doc">
 <header className="cvp-input-doc__hero"><div><span>Component 08 · Standardized</span><h1>Icon Small Button</h1></div><div><p>The 24px compact specialization of Icon Button for dense toolbars, inline row actions, and media overlays.</p><span className="cvp-input-doc__status">Compatibility alias · Ready</span></div></header>
 <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Canonical relationship</h2><p>IconSmallButton delegates to IconButton with <code>size="small"</code>; it does not maintain a second styling system.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live cvp-button-doc__live"><IconSmallButton aria-label="Edit"><Edit/></IconSmallButton></div><ol><li><b>1</b><span><strong>Alias</strong> Preserves existing product imports during migration.</span></li><li><b>2</b><span><strong>Target</strong> Fixed 24px compact target with 16px maximum glyph.</span></li><li><b>3</b><span><strong>Name</strong> Required action-oriented <code>aria-label</code>.</span></li></ol></div></section>
 <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Complete state model</h2><p>Focus is never suppressed or manually blurred; pointer and keyboard interactions share the canonical state contract.</p></div></header><div className="cvp-button-doc__states cvp-icon-doc__states">{states.map(([label,state,disabled,loading])=><article key={label}><span>{label}</span><IconSmallButton aria-label="Edit item" loading={loading} loadingLabel="Loading item" disabled={disabled} data-preview-state={state}><Edit/></IconSmallButton></article>)}</div></section>
 <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Variants and target comparison</h2><p>Remove is the only compact-specific usage pattern; other variants are inherited directly.</p></div></header><div className="cvp-icon-doc__matrix"><article><span>Default</span><IconSmallButton aria-label="Settings"><Settings/></IconSmallButton></article><article><span>Outline</span><IconSmallButton variant="outline" aria-label="Copy"><Copy/></IconSmallButton></article><article><span>Danger</span><IconSmallButton variant="danger" aria-label="Delete"><Trash2/></IconSmallButton></article><article><span>Rail gallery</span><IconSmallButton variant="rail-gallery" aria-label="Pin"><Pin/></IconSmallButton></article><article><span>Remove overlay</span><IconSmallButton variant="remove" aria-label="Remove item"><X/></IconSmallButton></article><article><span>Drag action</span><IconSmallButton aria-label="Reorder item"><GripVertical/></IconSmallButton></article><article><span>24px → 32px</span><div className="cvp-icon-small-doc__comparison"><IconSmallButton aria-label="Compact settings"><Settings/></IconSmallButton><IconButton aria-label="Default settings"><Settings/></IconButton></div></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Theme parity</h2><p>Compact and remove-overlay treatments resolve locally against both themes.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><IconSmallButton variant="remove" aria-label="Remove"><X/></IconSmallButton></article><article data-theme="light"><span>Light</span><IconSmallButton variant="remove" aria-label="Remove"><X/></IconSmallButton></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>05</b><div><h2>Token contract</h2><p>No Icon Small-specific visual tokens exist; the alias consumes the canonical Icon Button contract.</p></div></header><ComponentTokenContract label="Icon Small Button token contract" rows={tokenRows}/></section>
 <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Accessibility contract</h2></div></header><ul><li>Every instance requires an explicit action name.</li><li>Maintain sufficient separation between adjacent 24px targets.</li><li>Do not suppress focus for pointer input.</li><li>Use Medium Icon Button when target spacing is constrained.</li><li>Loading exposes busy state and blocks repeat activation.</li></ul></article><article className="cvp-input-doc__panel"><header><b>07</b><div><h2>Migration decisions</h2></div></header><ul><li>Existing imports may remain during migration.</li><li>New code should prefer <code>IconButton size="small"</code>.</li><li>Keep Remove limited to media/card removal overlays.</li><li>Do not create additional compact-only variants.</li><li>Consolidate usage when touching existing features.</li></ul></article></section>
 <footer className="cvp-input-doc__footer"><span>CVP compact button reference</span><p>Canonical alias · 24px target · Required name · Remove overlay</p></footer>
</main>}
