import React,{useState}from'react';
import{AtSign,Calendar,Clock}from'lucide-react';
import{MiscInput}from'./MiscInput';
import{ComponentTokenContract,ComponentTokenContractRow}from'./ComponentTokenContract';
import'./TextInputDocumentation.css';
import'./MiscInputDocumentation.css';

const rows:ComponentTokenContractRow[]=[
 {role:'Surface',token:'--cvp-misc-input-bg',source:'--cvp-input-bg',contract:'Shared input surface',activation:'Base'},
 {role:'Border',token:'--cvp-misc-input-border',source:'--cvp-input-border',contract:'1px semantic border',activation:'Base'},
 {role:'Text',token:'--cvp-misc-input-text',source:'--cvp-input-text',contract:'Theme-resolved',activation:'Base'},
 {role:'Placeholder',token:'--cvp-misc-input-placeholder',source:'--cvp-input-placeholder',contract:'4.5:1 minimum',activation:':placeholder'},
 {role:'Focus',token:'--cvp-misc-input-focus-ring',source:'--cvp-input-focus-ring',contract:'Border + outer halo',activation:':focus-visible'},
 {role:'Error',token:'--cvp-misc-input-error',source:'--cvp-color-border-error',contract:'Error border and message',activation:'error / variant="error"'},
 {role:'Warning',token:'--cvp-misc-input-warning',source:'--cvp-color-border-warning',contract:'Warning border and message',activation:'warning / variant="warning"'},
 {role:'Success',token:'--cvp-misc-input-success',source:'--cvp-color-border-success',contract:'Success border and message',activation:'success / variant="success"'},
 {role:'Height',token:'--cvp-misc-input-height',source:'--cvp-input-height',contract:'40px',activation:'All states'},
 {role:'Inline padding',token:'--cvp-misc-input-padding-x',source:'--cvp-input-padding-x',contract:'12px',activation:'Shell'},
 {role:'Add-on gap',token:'--cvp-misc-input-addon-gap',source:'--cvp-space-2',contract:'8px',activation:'Prefix / suffix / copy'},
];
const states=[['Default',{},'Project name'],['Hover',{'data-preview-state':'hover'},'Project name'],['Focus',{'data-preview-state':'focus'},'Project name'],['Error',{error:'Enter a valid project name'},'Invalid value'],['Warning',{warning:'This name is already in use'},'Existing name'],['Success',{success:'Project name is available'},'New project'],['Disabled',{disabled:true},'Unavailable']] as const;

export function MiscInputDocumentation(){const[value,setValue]=useState('Weather report');return <main className="cvp-input-doc cvp-misc-doc">
 <header className="cvp-input-doc__hero"><div><span>Component 11 · Standardized</span><h1>Misc Input</h1></div><div><p>The advanced single-line field for prefix/suffix content, copy actions, counters, and multi-intent validation.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
 <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Boundary and live behavior</h2><p>Use Text Input by default; use Misc Input only when the field needs slots, copy, counting, or warning/success states.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live"><MiscInput label="Report name" value={value} onChange={e=>setValue(e.target.value)} maxLength={40} showCharacterCount prefixElement={<AtSign/>} showCopy helperText="Use a recognizable internal name"/></div><ol><li><b>1</b><span><strong>Label row</strong> Label, optional field prefix, and live character count.</span></li><li><b>2</b><span><strong>Shared shell</strong> Input and add-ons share one focus and validation boundary.</span></li><li><b>3</b><span><strong>Support</strong> One associated helper or validation message.</span></li></ol></div></section>
 <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Complete state model</h2><p>Error takes precedence, followed by warning, success, and default guidance.</p></div></header><div className="cvp-misc-doc__states">{states.map(([label,props,placeholder])=><article key={label}><span>{label}</span><MiscInput label="Field label" placeholder={placeholder}{...props}/></article>)}</div></section>
 <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Advanced compositions</h2><p>Add-ons remain decorative; the copy action receives its own accessible name.</p></div></header><div className="cvp-misc-doc__compositions"><article><span>Prefix icon</span><MiscInput label="Start time" prefixElement={<Clock/>} placeholder="09:00"/></article><article><span>Suffix icon</span><MiscInput label="Due date" suffixElement={<Calendar/>} placeholder="DD/MM/YYYY"/></article><article><span>Field prefix + count</span><MiscInput label="Slug" fieldPrefix="cvp" maxLength={24} showCharacterCount defaultValue="forecast-card"/></article><article><span>Read-only + copy</span><MiscInput label="Generated ID" value="rail_01J8CVP" readOnly showCopy/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Theme parity</h2><p>Surface, text, placeholder, add-ons, intent colors, and focus resolve locally.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><MiscInput label="Project" placeholder="Project name"/></article><article data-theme="light"><span>Light</span><MiscInput label="Project" placeholder="Project name"/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>05</b><div><h2>Token contract</h2><p>The component extends the canonical input contract with registered advanced-field roles.</p></div></header><ComponentTokenContract label="Misc Input token contract" rows={rows}/></section>
 <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Accessibility contract</h2></div></header><ul><li>Associate every visible label through <code>htmlFor</code>.</li><li>Error sets <code>aria-invalid</code> and uses an alert message.</li><li>Support and count text join <code>aria-describedby</code>.</li><li>Decorative prefix and suffix content remain hidden.</li><li>Copy uses an action-oriented accessible name.</li></ul></article><article className="cvp-input-doc__panel"><header><b>07</b><div><h2>Usage decisions</h2></div></header><ul><li>Prefer Text Input when no advanced feature is needed.</li><li>Show one validation intent at a time.</li><li>Use character count only when a meaningful limit exists.</li><li>Use copy primarily with read-only or generated values.</li><li>Do not place arbitrary interactive controls in add-on slots.</li></ul></article></section>
 <footer className="cvp-input-doc__footer"><span>CVP advanced field reference</span><p>Shared input base · Slots · Copy · Count · Four validation states</p></footer>
</main>}
