import React,{useState}from'react';
import{MultiSelect,MultiSelectOption}from'./MultiSelect';
import{ComponentTokenContract,ComponentTokenContractRow}from'./ComponentTokenContract';
import'./TextInputDocumentation.css';
import'./MultiSelectDocumentation.css';

const options:MultiSelectOption[]=[{value:'forecast',label:'Forecast'},{value:'observations',label:'Observations'},{value:'warnings',label:'Warnings'},{value:'climate',label:'Climate records'},{value:'experimental',label:'Experimental',disabled:true}];
const rows:ComponentTokenContractRow[]=[
 {role:'Field surface',token:'--cvp-multi-select-bg',source:'--cvp-input-bg',contract:'Shared input surface',activation:'Base'},
 {role:'Field boundary',token:'--cvp-multi-select-border',source:'--cvp-input-border',contract:'Shared input border',activation:'Base'},
 {role:'Focus',token:'--cvp-multi-select-focus-ring',source:'--cvp-input-focus-ring',contract:'Canonical visible ring',activation:':focus-within / open'},
 {role:'Placeholder',token:'--cvp-multi-select-placeholder',source:'--cvp-input-placeholder',contract:'4.5:1 minimum',activation:'Empty'},
 {role:'Tag surface',token:'--cvp-multi-select-tag-bg',source:'--cvp-color-brand-default',contract:'Theme-resolved brand',activation:'Selected value'},
 {role:'Tag text',token:'--cvp-multi-select-tag-text',source:'--cvp-color-text-on-brand',contract:'4.5:1 minimum',activation:'Selected value'},
 {role:'Selection summary',token:'--cvp-multi-select-meta-font-size',source:'--cvp-font-size-sm',contract:'13px interactive metadata',activation:'Open popup'},
 {role:'Popup',token:'--cvp-multi-select-popup-bg',source:'--cvp-menu-bg',contract:'Overlay surface',activation:'Open'},
 {role:'Selected option',token:'--cvp-multi-select-option-selected',source:'--cvp-menu-item-bg-active',contract:'Menu selected surface',activation:'aria-selected=true'},
 {role:'Error',token:'--cvp-multi-select-error',source:'--cvp-input-border-error',contract:'Error boundary',activation:'error'},
 {role:'Height',token:'--cvp-multi-select-min-height',source:'--cvp-input-height',contract:'40px minimum; grows with tags',activation:'Shell'},
];

export function MultiSelectDocumentation(){const[value,setValue]=useState(['forecast','warnings']);return <main className="cvp-input-doc cvp-multi-doc">
 <header className="cvp-input-doc__hero"><div><span>Component 13 · Standardized</span><h1>Multi Select</h1></div><div><p>A searchable multiple-choice field with removable tags, selection limits, optional creation, and a governed menu.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
 <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>The field grows when values wrap; it is not forced into a fixed single-line height.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live"><MultiSelect label="Data products" description="Choose one or more products." options={options} value={value} onChange={setValue} placeholder="Choose products"/></div><ol><li><b>1</b><span><strong>Field label</strong> Programmatically names the searchable combobox.</span></li><li><b>2</b><span><strong>Value tags</strong> Show selections with individually named removal actions.</span></li><li><b>3</b><span><strong>Search and menu</strong> Filters a multi-select listbox and exposes selection state.</span></li></ol></div></section>
 <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Complete field states</h2><p>Hover, focus, error, disabled, populated, clear-hover, and maximum-selection behavior use the shared form hierarchy.</p></div></header><div className="cvp-multi-doc__states"><article><span>Default</span><MultiSelect label="Products" options={options} allowCreate={false}/></article><article><span>Hover</span><MultiSelect label="Products" options={options} previewState="hover" allowCreate={false}/></article><article><span>Focus</span><MultiSelect label="Products" options={options} previewState="focus" allowCreate={false}/></article><article><span>Clear action hover</span><MultiSelect label="Products" options={options} defaultValue={['forecast','climate']} previewState="clear-hover" allowCreate={false}/></article><article><span>Error</span><MultiSelect label="Products" options={options} error="Select at least one product." allowCreate={false}/></article><article><span>Disabled</span><MultiSelect label="Products" options={options} defaultValue={['forecast']} disabled allowCreate={false}/></article><article><span>Maximum reached</span><MultiSelect label="Products" options={options} defaultValue={['forecast','warnings']} maxSelection={2} description="2 selections maximum" allowCreate={false}/></article><article><span>Required</span><MultiSelect label="Products" options={options} required description="Required" allowCreate={false}/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Behavior contract</h2><p>Search, creation, bulk actions, and limits remain explicit product decisions.</p></div></header><div className="cvp-multi-doc__behaviors"><article><span>Search + create</span><MultiSelect label="Custom tags" options={options.slice(0,3)} placeholder="Search or create" allowCreate/></article><article><span>Limited controlled value</span><MultiSelect label="Featured products" options={options} value={value} onChange={setValue} maxSelection={3} allowCreate={false}/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Theme parity</h2><p>Tags, field, menu roles, placeholder, support, error, and focus resolve through the active theme.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><MultiSelect label="Products" options={options} defaultValue={['forecast']} allowCreate={false}/></article><article data-theme="light"><span>Light</span><MultiSelect label="Products" options={options} defaultValue={['forecast']} allowCreate={false}/></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>05</b><div><h2>Token contract</h2><p>Multi Select extends the canonical input and menu contracts with registered tag and popup roles.</p></div></header><ComponentTokenContract label="Multi Select token contract" rows={rows}/></section>
 <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>DOM and accessibility contract</h2></div></header><ul><li>The visible label names the search combobox through <code>htmlFor</code>.</li><li>The popup is a multi-select listbox; options expose <code>aria-selected</code> and disabled state.</li><li>Each removal and clear action has a specific accessible name and keyboard focus.</li><li>Error uses <code>aria-invalid</code>, an alert, and composed <code>aria-describedby</code>.</li><li>Escape closes; arrows move through options; Enter or Space toggles the focused option.</li></ul></article><article className="cvp-input-doc__panel"><header><b>07</b><div><h2>Usage decisions</h2></div></header><ul><li>Use Select for one value and Checkbox for short visible sets.</li><li>Enable creation only when arbitrary values are valid domain data.</li><li>State the maximum when selection is limited.</li><li>Do not fix the field height when tags may wrap.</li><li>Submit repeated hidden inputs when a form name is supplied.</li></ul></article></section>
 <footer className="cvp-input-doc__footer"><span>CVP multi-select reference</span><p>Input contract · Menu contract · Tags · Search · Limits · Creation</p></footer>
 </main>}
