import React, { useState } from 'react';
import { ArrowUpDown, Plus } from 'lucide-react';
import { OutlineButton } from './OutlineButton';
import { ComponentTokenContract, ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './PrimaryButtonDocumentation.css';
import './OutlineButtonDocumentation.css';

const tokenRows:ComponentTokenContractRow[]=[
  {role:'Label',token:'--cvp-button-outline-text',source:'--cvp-color-text-primary',contract:'Theme-resolved foreground',activation:'Base'},
  {role:'Border',token:'--cvp-button-outline-border',source:'--cvp-color-border-default',contract:'1px solid',activation:'Base'},
  {role:'Hover surface',token:'--cvp-button-outline-bg-hover',source:'--cvp-color-surface-hover',contract:'Subtle surface',activation:':hover'},
  {role:'Hover border',token:'--cvp-button-outline-border-hover',source:'--cvp-focus-border-color',contract:'Accent border',activation:':hover'},
  {role:'Pressed',token:'--cvp-button-outline-bg-active',source:'--cvp-color-surface-active',contract:'Active surface + 1px offset',activation:':active'},
  {role:'Focus',token:'--cvp-button-outline-focus-ring',source:'--cvp-border-focus-ring',contract:'Border + outer halo',activation:':focus-visible'},
  {role:'Disabled label',token:'--cvp-button-outline-text-disabled',source:'--cvp-color-text-disabled',contract:'Theme resolved',activation:':disabled'},
  {role:'Default height',token:'--cvp-button-outline-height',source:'--cvp-space-800',contract:'40px',activation:'size="medium"'},
  {role:'Small height',token:'--cvp-button-outline-height-small',source:'--cvp-space-8',contract:'32px',activation:'size="small"'},
  {role:'Large height',token:'--cvp-button-outline-height-large',source:'--cvp-space-900',contract:'48px',activation:'size="large"'},
  {role:'Shape',token:'--cvp-button-outline-radius',source:'--cvp-radius-sm',contract:'4px',activation:'Small / medium'},
  {role:'Loading indicator',token:'--cvp-button-outline-spinner-size',source:'--cvp-space-4',contract:'16px / 2px stroke',activation:'loading={true}'},
];
const states=[['Default',undefined,false,false],['Hover','hover',false,false],['Pressed','active',false,false],['Focus','focus',false,false],['Loading',undefined,false,true],['Disabled',undefined,true,false]] as const;

export function OutlineButtonDocumentation(){
  const [sortDirection,setSortDirection]=useState<'ASC'|'DESC'>('DESC');
  const [logicalOperator,setLogicalOperator]=useState<'AND'|'OR'>('AND');
  return <main className="cvp-input-doc cvp-button-doc">
  <header className="cvp-input-doc__hero"><div><span>Component 06 · Standardized</span><h1>Outline Button</h1></div><div><p>A low-emphasis bordered action for cancellation, navigation, and supporting choices within the CVP button hierarchy.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
  <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>Transparent resting surface, semantic border and label, optional inline icon, and reserved loading layer.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live cvp-button-doc__live"><OutlineButton>Cancel</OutlineButton></div><ol><li><b>1</b><span><strong>Root</strong> Native <code>button</code> retains expected activation.</span></li><li><b>2</b><span><strong>Border</strong> Creates hierarchy without a persistent filled surface.</span></li><li><b>3</b><span><strong>Label</strong> Supplies a concise accessible name.</span></li></ol></div></section>
  <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Complete state model</h2><p>Hover and pressed surfaces reinforce interaction while focus remains independently visible.</p></div></header><div className="cvp-button-doc__states">{states.map(([label,state,disabled,loading])=><article key={label}><span>{label}</span><OutlineButton disabled={disabled} loading={loading} data-preview-state={state}>Cancel</OutlineButton></article>)}</div></section>
  <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Sizes and variants</h2><p>Shared button-family dimensions plus a dashed “add region” treatment.</p></div></header><div className="cvp-button-doc__sizes"><article><span>Small · 32px</span><OutlineButton size="small">Back</OutlineButton></article><article><span>Medium · 40px</span><OutlineButton>Cancel</OutlineButton></article><article><span>Large · 48px</span><OutlineButton size="large">Review later</OutlineButton></article><article><span>Compact · 32px</span><OutlineButton variant="compact">Reset</OutlineButton></article><article><span>Dotted · additive</span><OutlineButton variant="dotted"><Plus size={16}/> Add filter</OutlineButton></article></div><div className="cvp-outline-doc__query"><div><h3>Query configuration variants</h3><p>Compact toggle actions for sort direction and logical grouping. Click either control to change its value.</p></div><div className="cvp-outline-doc__query-actions"><OutlineButton variant="compact"><Plus size={14}/> Add filter</OutlineButton><OutlineButton variant="compact" aria-pressed={sortDirection==='ASC'} aria-label={`Sort direction: ${sortDirection}`} onClick={()=>setSortDirection(value=>value==='ASC'?'DESC':'ASC')}><ArrowUpDown size={14}/>{sortDirection}</OutlineButton><OutlineButton variant="compact" aria-pressed={logicalOperator==='OR'} aria-label={`Logical operator: ${logicalOperator}`} onClick={()=>setLogicalOperator(value=>value==='AND'?'OR':'AND')}>{logicalOperator}</OutlineButton></div></div></section>
  <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Theme parity</h2><p>Border, label, state surfaces, and focus ring resolve through semantic theme roles.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><OutlineButton>Cancel</OutlineButton></article><article data-theme="light"><span>Light</span><OutlineButton>Cancel</OutlineButton></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>05</b><div><h2>Token contract</h2><p>Every visual decision resolves through a registered Tier 3 outline-button token.</p></div></header><ComponentTokenContract label="Outline Button token contract" rows={tokenRows}/></section>
  <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Accessibility contract</h2></div></header><ul><li>Use native button semantics and a visible label.</li><li>Do not rely on the border alone to communicate state.</li><li>Focus uses the shared non-color-only ring.</li><li>Loading exposes <code>aria-busy</code> and prevents repeat activation.</li><li>Reduced motion removes state transitions.</li></ul></article><article className="cvp-input-doc__panel"><header><b>07</b><div><h2>Usage decisions</h2></div></header><ul><li>Use for Cancel, Back, Reset, and low-emphasis alternatives.</li><li>Use Secondary when an action needs stronger emphasis.</li><li>Reserve dotted borders for additive or empty-region actions.</li><li>Do not mix border styles in the same action group.</li><li>Use Text Button for the quietest action level.</li></ul></article></section>
  <footer className="cvp-input-doc__footer"><span>CVP button family reference</span><p>Native button · Canonical tokens · Loading · Variants · Themes</p></footer>
</main>}
