import React from 'react';
import { ListFilter, Maximize2, PanelLeft, Rows3 } from 'lucide-react';
import { PrimaryButton } from './PrimaryButton';
import { OutlineButton } from './OutlineButton';
import './RailDetailsDocumentation.css';

export function RailDetailsDocumentation() {
  const openFullPage = (theme: 'dark' | 'light', variant?: 'empty' | 'locked') => window.open(`${window.location.pathname}?page=rail-details-full&theme=${theme}${variant === 'empty' ? '&empty=1' : variant === 'locked' ? '&locked=1' : ''}`, '_blank');
  return <main className="rail-details-docs documentation-container">
    <header className="rail-details-docs__hero"><span className="rail-details-docs__eyebrow">Pages</span><h1>Rail Details</h1><p>An integration workspace for configuring a content rail and reviewing its live composition. This page demonstrates how the standardized foundations and components behave together under production-like density.</p><div className="rail-details-docs__preview-actions"><PrimaryButton onClick={() => openFullPage('dark')}><Maximize2 size={15} /> Open dark preview</PrimaryButton><OutlineButton onClick={() => openFullPage('light')}><Maximize2 size={15} /> Open light preview</OutlineButton><OutlineButton onClick={() => openFullPage('dark', 'empty')}><Maximize2 size={15} /> Open empty rail · dark</OutlineButton><OutlineButton onClick={() => openFullPage('light', 'empty')}><Maximize2 size={15} /> Open empty rail · light</OutlineButton><OutlineButton onClick={() => openFullPage('dark', 'locked')}><Maximize2 size={15} /> Open query locked · dark</OutlineButton><OutlineButton onClick={() => openFullPage('light', 'locked')}><Maximize2 size={15} /> Open query locked · light</OutlineButton></div></header>
    <section className="rail-details-docs__section" aria-labelledby="rail-details-composition"><div className="rail-details-docs__section-heading"><span>Integration composition</span><h2 id="rail-details-composition">Built from the system</h2></div><div className="rail-details-docs__grid"><article><PanelLeft size={20} /><strong>Configuration pane</strong><p>Tabs, Text Input, Number Input, Select, Checkbox, Search Field, Sort Control, and a confirmed destructive action share one compact form rhythm.</p></article><article><Rows3 size={20} /><strong>Content Query</strong><p>Tag Filter and Multi Select support program type, tags, media availability, release year, and subscription-package criteria; each contextual label uses the shared Tooltip pattern.</p></article><article><ListFilter size={20} /><strong>Empty rail choices</strong><p>The elevated empty state routes algorithmic curation to Content Query and manual curation to Content Browser Modal.</p></article></div></section>
    <section className="rail-details-docs__section rail-details-docs__note"><strong>Query locked pattern</strong><p>When every available slot is occupied by manual content, preserve the standard Content Query underneath a scoped overlay rather than turning each control into a separate disabled state. An inline information banner explains the condition and when filters become available again.</p></section>
    <section className="rail-details-docs__section rail-details-docs__note"><strong>Review intent</strong><p>This page intentionally has no additional token contract. It is the natural integration audit for the component contracts already documented on their individual pages.</p></section>
  </main>;
}
