import React, { useState } from 'react';
import { BarChart3, Grid2X2, List, Rows3 } from 'lucide-react';
import { Segmented, SegmentedOption } from './Segmented';
import { ComponentTokenContract, ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './SegmentedDocumentation.css';

const rows:ComponentTokenContractRow[]=[
 {role:'Container surface',token:'--cvp-segmented-bg',source:'--cvp-color-surface-sunken',contract:'Groups one selection set',activation:'Default variant'},
 {role:'Option text',token:'--cvp-segmented-text',source:'--cvp-color-text-muted',contract:'4.5:1 minimum',activation:'Unselected'},
 {role:'Selected surface',token:'--cvp-segmented-bg-selected',source:'--cvp-color-surface-raised',contract:'Persistent non-color-only cue',activation:'aria-checked=true'},
 {role:'Color selection',token:'--cvp-segmented-color-bg-selected',source:'--cvp-color-brand-default',contract:'Theme-safe emphasis',activation:'Color variant selected'},
 {role:'Color selection text',token:'--cvp-segmented-color-text-selected',source:'--cvp-color-text-on-brand',contract:'4.5:1 minimum',activation:'Color variant selected'},
 {role:'Focus',token:'--cvp-segmented-focus-ring',source:'--cvp-border-focus-ring',contract:'Canonical visible ring',activation:':focus-visible'},
 {role:'Container radius',token:'--cvp-segmented-container-radius',source:'--cvp-radius-md',contract:'6px grouping shape',activation:'All sizes'},
 {role:'Medium height',token:'--cvp-segmented-height-medium',source:'--cvp-space-900',contract:'48px option target',activation:'Medium'},
];

const basic:SegmentedOption[]=[{value:'list',label:'List',icon:<List/>},{value:'grid',label:'Grid',icon:<Grid2X2/>},{value:'rows',label:'Rows',icon:<Rows3/>}];
export function SegmentedDocumentation(){
 const[value,setValue]=useState('list');
 return <main className="cvp-input-doc cvp-segmented-doc">
  <header className="cvp-input-doc__hero"><div><span>Navigation 05 · Standardized</span><h1>Segmented</h1></div><div><p>A compact, mutually exclusive choice control for changing views, scopes, or presentation modes without revealing separate panels.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
  <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>The group, options, selection, and optional icons communicate one immediate choice.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live"><Segmented options={basic} value={value} onChange={setValue} ariaLabel="Content layout"/><p className="cvp-segmented-doc__result">Selected view: <strong>{value}</strong></p></div><ol><li><b>1</b><span><strong>Radio group</strong> Names one mutually exclusive decision.</span></li><li><b>2</b><span><strong>Option</strong> Exposes its selected and disabled states.</span></li><li><b>3</b><span><strong>Selected surface</strong> Uses contrast, elevation, and weight—not color alone.</span></li><li><b>4</b><span><strong>Optional icon</strong> Supplements a persistent text label.</span></li></ol></div></section>
  <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Variants and states</h2><p>Size, emphasis, width, and availability remain explicit component properties.</p></div></header><div className="cvp-segmented-doc__variants"><article><span>Small</span><Segmented size="small" options={[{value:'day',label:'Day'},{value:'week',label:'Week'},{value:'month',label:'Month'}]} defaultValue="week"/></article><article><span>Medium · default</span><Segmented options={basic} defaultValue="list"/></article><article><span>Large</span><Segmented size="large" options={[{value:'edit',label:'Edit'},{value:'preview',label:'Preview'}]} defaultValue="edit"/></article><article><span>Color emphasis</span><Segmented variant="color" options={[{value:'analytics',label:'Analytics',icon:<BarChart3/>},{value:'insights',label:'Insights'},{value:'reports',label:'Reports'}]} defaultValue="analytics"/></article><article><span>Full width</span><Segmented fullWidth options={[{value:'list',label:'List view'},{value:'grid',label:'Grid view'}]} defaultValue="list"/></article><article><span>Disabled option</span><Segmented options={[{value:'active',label:'Active'},{value:'pending',label:'Pending'},{value:'archived',label:'Archived',disabled:true}]} defaultValue="active"/></article><article><span>Disabled group</span><Segmented disabled options={basic} defaultValue="list"/></article><article><span>Overflow</span><Segmented options={['All','Editorial','Sports','News','Kids','Movies'].map(label=>({value:label.toLowerCase(),label}))} defaultValue="all"/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Theme parity</h2><p>Group, selection, icons, focus, hover, and disabled states resolve from the same contract.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><Segmented options={basic} defaultValue="grid"/></article><article data-theme="light"><span>Light</span><Segmented options={basic} defaultValue="grid"/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Token contract</h2><p>Segmented owns a registered Tier 3 contract for both neutral and color-emphasis variants.</p></div></header><ComponentTokenContract label="Segmented token contract" rows={rows}/></section>
  <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>05</b><div><h2>Accessibility contract</h2></div></header><ul><li>The component uses <code>radiogroup</code> and <code>radio</code> semantics.</li><li>The group requires a meaningful accessible label.</li><li>Arrow keys select and focus the next enabled option.</li><li>Home and End jump to the first and last enabled options.</li><li>Only the selected option participates in the page tab order.</li><li>Disabled options and groups remain perceivable.</li></ul></article><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Usage decisions</h2></div></header><ul><li>Use for two to five immediate, mutually exclusive choices.</li><li>Use Tabs when each choice owns a labelled content panel.</li><li>Keep labels short and semantically parallel.</li><li>Pair icons with text unless space is severely constrained.</li><li>Use the color variant sparingly for higher emphasis.</li><li>Allow horizontal scrolling instead of wrapping options.</li></ul></article></section>
  <footer className="cvp-input-doc__footer"><span>CVP navigation family</span><p>Radio-group semantics · Sizes · Emphasis · Full width · Overflow</p></footer>
 </main>;
}
