import React, { useState } from 'react';
import { Bell, Settings, Shield, User } from 'lucide-react';
import { Tabs } from './Tabs';
import { ComponentTokenContract, ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './TabsDocumentation.css';

const rows:ComponentTokenContractRow[]=[
 {role:'Ancestor text',token:'--cvp-tabs-text',source:'--cvp-color-text-muted',contract:'4.5:1 minimum',activation:'Unselected'},
 {role:'Selected text',token:'--cvp-tabs-text-active',source:'--cvp-color-text-primary',contract:'Highest label emphasis',activation:'aria-selected=true'},
 {role:'Selection indicator',token:'--cvp-tabs-indicator',source:'--cvp-color-brand-default',contract:'2px persistent cue',activation:'aria-selected=true'},
 {role:'Hover surface',token:'--cvp-tabs-tab-bg-hover',source:'--cvp-color-surface-hover',contract:'Subtle interaction feedback',activation:':hover'},
 {role:'Focus',token:'--cvp-tabs-focus-ring',source:'--cvp-border-focus-ring',contract:'Canonical visible ring',activation:':focus-visible'},
 {role:'Disabled text',token:'--cvp-tabs-text-disabled',source:'--cvp-color-text-disabled',contract:'Non-interactive state',activation:':disabled'},
 {role:'Tab height',token:'--cvp-tabs-tab-height',source:'--cvp-space-900',contract:'48px',activation:'Horizontal and vertical'},
 {role:'Panel gap',token:'--cvp-tabs-panel-gap',source:'--cvp-space-6',contract:'24px',activation:'Horizontal'},
];

const panel=(title:string,copy:string)=><div className="cvp-tabs-doc__content"><strong>{title}</strong><p>{copy}</p></div>;
const primaryTabs=[{id:'overview',label:'Overview',content:panel('Overview','A concise summary of this workspace and its current configuration.')},{id:'activity',label:'Activity',content:panel('Activity','Recent changes, publishing events, and operator actions.')},{id:'settings',label:'Settings',content:panel('Settings','Configuration that belongs to this view rather than global navigation.')},{id:'disabled',label:'Disabled',content:null,disabled:true}];

export function TabsDocumentation(){
 const[active,setActive]=useState('overview');
 return <main className="cvp-input-doc cvp-tabs-doc">
  <header className="cvp-input-doc__hero"><div><span>Navigation 03 · Standardized</span><h1>Tabs</h1></div><div><p>A local navigation pattern for switching between peer views without changing the user’s broader location.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
  <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>Selection, focus, and the associated panel remain independently perceivable.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live"><Tabs tabs={primaryTabs} activeTab={active} onTabChange={setActive}/><p className="cvp-tabs-doc__result">Active tab: <strong>{active}</strong></p></div><ol><li><b>1</b><span><strong>Tab list</strong> Defines a single set of peer destinations.</span></li><li><b>2</b><span><strong>Tab</strong> Provides label, selection, focus, and disabled states.</span></li><li><b>3</b><span><strong>Indicator</strong> Reinforces selection beyond text color.</span></li><li><b>4</b><span><strong>Panel</strong> Is labelled by its controlling tab and remains focusable.</span></li></ol></div></section>
  <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Variants and activation</h2><p>Orientation and keyboard activation are explicit behavioral choices, not styling forks.</p></div></header><div className="cvp-tabs-doc__variants"><article><span>Icons · automatic activation</span><Tabs tabs={[{id:'profile',label:<><User/>Profile</>,content:panel('Profile','Personal identity and preferences.')},{id:'alerts',label:<><Bell/>Notifications</>,content:panel('Notifications','Delivery and alert preferences.')},{id:'security',label:<><Shield/>Security</>,content:panel('Security','Authentication and access configuration.')} ]}/></article><article><span>Manual activation</span><Tabs activationMode="manual" ariaLabel="Manual activation example" tabs={[{id:'summary',label:'Summary',content:panel('Summary','Arrow keys move focus; Enter or Space changes the panel.')},{id:'details',label:'Details',content:panel('Details','Useful when switching panels is computationally expensive.')},{id:'history',label:'History',content:panel('History','Focus and selection are intentionally separate.')} ]}/></article><article><span>Vertical</span><Tabs orientation="vertical" ariaLabel="Settings sections" tabs={[{id:'general',label:<><Settings/>General</>,content:panel('General','Primary settings for this workspace.')},{id:'people',label:<><User/>People</>,content:panel('People','Membership and permissions.')},{id:'privacy',label:<><Shield/>Privacy</>,content:panel('Privacy','Data access and retention.')} ]}/></article><article><span>Overflow</span><Tabs ariaLabel="Overflow example" tabs={['Overview','Editorial','Availability','Localization','Rights','Distribution','Analytics','History'].map((label,index)=>({id:`overflow-${index}`,label,content:panel(label,'Horizontally scrollable tab list with a stable single row.')}))}/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Theme parity</h2><p>Text, divider, indicator, focus, hover, and disabled roles resolve through the same contract.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><Tabs tabs={primaryTabs.slice(0,3)}/></article><article data-theme="light"><span>Light</span><Tabs tabs={primaryTabs.slice(0,3)}/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Token contract</h2><p>Tabs owns a registered Tier 3 contract with no local color, spacing, typography, or motion values.</p></div></header><ComponentTokenContract label="Tabs token contract" rows={rows}/></section>
  <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>05</b><div><h2>Accessibility contract</h2></div></header><ul><li>Tab, tablist, and tabpanel relationships use unique instance IDs.</li><li>Only the selected tab participates in roving tab order.</li><li>Arrow keys follow orientation; Home and End jump boundaries.</li><li>Automatic and manual activation modes are supported.</li><li>Disabled tabs are skipped by keyboard navigation.</li><li>Selection remains visible without relying on color alone.</li></ul></article><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Usage decisions</h2></div></header><ul><li>Use tabs for peer content, not sequential workflow steps.</li><li>Keep labels concise and stable.</li><li>Prefer automatic activation for lightweight local panels.</li><li>Use manual activation when panels load slowly.</li><li>Allow horizontal scrolling rather than wrapping tabs.</li><li>Avoid hiding critical actions inside infrequently visited panels.</li></ul></article></section>
  <footer className="cvp-input-doc__footer"><span>CVP navigation family</span><p>Roving focus · Automatic/manual activation · Orientation · Overflow</p></footer>
 </main>;
}
