import React, { useState } from 'react';
import { TagFilter, TagFilterSection } from './TagFilter';
import { ComponentTokenContract, ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './TagFilterDocumentation.css';

const rows:ComponentTokenContractRow[]=[
 {role:'Option text',token:'--cvp-tag-filter-option-text',source:'--cvp-color-text-secondary',contract:'4.5:1 minimum',activation:'Unselected'},
 {role:'Option boundary',token:'--cvp-tag-filter-option-border',source:'--cvp-color-border-default',contract:'Subtle idle edge',activation:'Unselected'},
 {role:'Selected surface',token:'--cvp-tag-filter-selected-bg',source:'--cvp-color-brand-default',contract:'Persistent pressed state',activation:'aria-pressed=true'},
 {role:'Selected text',token:'--cvp-tag-filter-selected-text',source:'--cvp-color-text-on-brand',contract:'4.5:1 minimum',activation:'aria-pressed=true'},
 {role:'Focus',token:'--cvp-tag-filter-focus-ring',source:'--cvp-border-focus-ring',contract:'Canonical visible ring',activation:':focus-visible'},
 {role:'Disabled boundary',token:'--cvp-tag-filter-disabled-border',source:'--cvp-color-border-disabled',contract:'Non-interactive state',activation:':disabled'},
 {role:'Tag height',token:'--cvp-tag-filter-height',source:'--cvp-space-8',contract:'32px compact filter target',activation:'All options'},
 {role:'Facet label',token:'--cvp-tag-filter-title-size',source:'--cvp-input-label-size',contract:'Matches Select, Text Input, and Multi Select labels',activation:'Every facet heading'},
 {role:'Label-to-tags gap',token:'--cvp-tag-filter-title-gap',source:'--cvp-input-field-gap',contract:'4px shared form-field spacing',activation:'Between each facet label and its tags'},
 {role:'Section gap',token:'--cvp-tag-filter-section-gap',source:'--cvp-space-8',contract:'32px',activation:'Between groups'},
];

const sections:TagFilterSection[]=[{id:'asset',title:'Asset type',options:[{id:'primary-video',label:'Primary video'},{id:'secondary-video',label:'Secondary video'},{id:'audio',label:'Audio track'},{id:'subtitles',label:'Subtitle track'},{id:'metadata',label:'Metadata file'}]},{id:'quality',title:'Encoding profile',options:[{id:'4k',label:'4K UHD'},{id:'1080p',label:'1080p HD'},{id:'720p',label:'720p HD'},{id:'mobile',label:'Mobile'},{id:'legacy',label:'Legacy',disabled:true}]}];
const statusSections:TagFilterSection[]=[{id:'status',title:'Content status',options:[{id:'published',label:'Published'},{id:'draft',label:'Draft'},{id:'scheduled',label:'Scheduled'},{id:'archived',label:'Archived'}]}];

export function TagFilterDocumentation(){
 const[selected,setSelected]=useState<string[]>(['primary-video','4k']);
 const[emptyControlled,setEmptyControlled]=useState<string[]>([]);
 return <main className="cvp-input-doc cvp-tag-filter-doc">
  <header className="cvp-input-doc__hero"><div><span>Navigation 06 · Standardized</span><h1>Tag Filter</h1></div><div><p>A visible multi-selection filter for compact, predefined option sets grouped by meaningful facets.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
  <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and live behavior</h2><p>Each tag is one toggle button; its X is a selected-state removal cue, not a nested control.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live"><TagFilter sections={sections} selectedOptions={selected} onSelectionChange={setSelected} showSelectionCount/><p className="cvp-tag-filter-doc__result">Selection: <strong>{selected.join(', ')||'None'}</strong></p></div><ol><li><b>1</b><span><strong>Facet label</strong> Uses the shared form-label contract, including the 4px label-to-tags gap.</span></li><li><b>2</b><span><strong>Toggle tag</strong> Uses native button behavior and <code>aria-pressed</code>.</span></li><li><b>3</b><span><strong>Selected cue</strong> Combines brand surface, weight, and an X icon.</span></li><li><b>4</b><span><strong>Selection summary</strong> Optionally announces count changes.</span></li></ol></div></section>
  <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>States and constraints</h2><p>Availability and selection limits remain visible and predictable.</p></div></header><div className="cvp-tag-filter-doc__variants"><article><span>Uncontrolled defaults</span><TagFilter sections={statusSections} defaultSelectedOptions={['published']}/></article><article><span>Controlled empty state</span><TagFilter sections={statusSections} selectedOptions={emptyControlled} onSelectionChange={setEmptyControlled}/></article><article><span>Maximum two</span><TagFilter sections={statusSections} defaultSelectedOptions={['published']} maxSelections={2} showSelectionCount/></article><article><span>Disabled group</span><TagFilter sections={statusSections} defaultSelectedOptions={['published','draft']} disabled/></article><article><span>Disabled option</span><TagFilter sections={sections.slice(1)} defaultSelectedOptions={['4k']}/></article><article><span>Long labels and wrapping</span><TagFilter sections={[{id:'rights',title:'Rights availability',options:[{id:'global',label:'Available in all territories'},{id:'restricted',label:'Regionally restricted'},{id:'expired',label:'Rights window expired'}]}]}/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Theme parity</h2><p>Text, borders, selection, hover, focus, removal, and disabled roles resolve semantically.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><TagFilter sections={statusSections} defaultSelectedOptions={['published','draft']}/></article><article data-theme="light"><span>Light</span><TagFilter sections={statusSections} defaultSelectedOptions={['published','draft']}/></article></div></section>
  <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Token contract</h2><p>Tag Filter owns registered Tier 3 roles for facets, tags, selection, limits, typography, and motion.</p></div></header><ComponentTokenContract label="Tag Filter token contract" rows={rows}/></section>
  <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>05</b><div><h2>Accessibility contract</h2></div></header><ul><li>Facet headings label their option groups.</li><li>Every option is a native toggle button with <code>aria-pressed</code>.</li><li>No interactive element is nested inside another.</li><li>Selected state is communicated by more than color.</li><li>Limit-disabled options use native disabled behavior.</li><li>The optional count summary uses a polite live region.</li></ul></article><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Usage decisions</h2></div></header><ul><li>Use when all relevant filter choices should remain visible.</li><li>Use Multi Select for larger searchable datasets.</li><li>Keep facets independent and labels concise.</li><li>Use a selection limit only when the domain requires it.</li><li>Avoid more than roughly twenty options per facet.</li><li>Do not use selected tags as destructive deletion controls.</li></ul></article></section>
  <footer className="cvp-input-doc__footer"><span>CVP navigation family</span><p>Multi-selection · Facets · Limits · Native toggle semantics</p></footer>
 </main>;
}
