import React,{useState} from 'react';
import { ChevronDown, ChevronUp, FileText, Grid } from 'lucide-react';
import { TextButton } from './TextButton';
import { ComponentTokenContract,ComponentTokenContractRow } from './ComponentTokenContract';
import './TextInputDocumentation.css';
import './PrimaryButtonDocumentation.css';
import './TextButtonDocumentation.css';

const rows:ComponentTokenContractRow[]=[
 {role:'Default label',token:'--cvp-button-text-color',source:'--cvp-color-text-link-default',contract:'Theme-safe action blue',activation:'variant="default"'},
 {role:'Hover label',token:'--cvp-button-text-color-hover',source:'--cvp-color-text-link-hover',contract:'Higher emphasis',activation:':hover'},
 {role:'Focus',token:'--cvp-button-text-focus-ring',source:'--cvp-border-focus-ring',contract:'Visible halo',activation:':focus-visible'},
 {role:'Disabled',token:'--cvp-button-text-color-disabled',source:'--cvp-color-text-disabled',contract:'Theme resolved',activation:':disabled'},
 {role:'Secondary label',token:'--cvp-button-text-secondary-color',source:'--cvp-color-text-muted',contract:'Neutral action',activation:'variant="secondary"'},
 {role:'Toggle label',token:'--cvp-button-text-toggle-color',source:'--cvp-color-text-link-default',contract:'Interactive disclosure',activation:'variant="toggle"'},
 {role:'Minimal label',token:'--cvp-button-text-minimal-color',source:'--cvp-color-text-muted',contract:'Inline contextual action',activation:'variant="minimal"'},
 {role:'Nav label',token:'--cvp-button-text-nav-color',source:'--cvp-color-nav-text',contract:'Navigation role',activation:'variant="nav"'},
 {role:'Nav active',token:'--cvp-button-text-nav-bg-active',source:'--cvp-color-surface-subtle',contract:'Current destination',activation:'active={true}'},
 {role:'Nav active hover',token:'--cvp-button-text-nav-bg-hover',source:'--cvp-color-surface-hover',contract:'Compact disabled-link hover treatment',activation:'variant="nav" active hover'},
 {role:'Loading',token:'--cvp-button-text-spinner-size',source:'--cvp-space-4',contract:'16px / 2px stroke',activation:'loading={true}'},
];
const states=[['Default',undefined,false,false],['Hover','hover',false,false],['Pressed','active',false,false],['Focus','focus',false,false],['Loading',undefined,false,true],['Disabled',undefined,true,false]] as const;

export function TextButtonDocumentation(){const[expanded,setExpanded]=useState(false);const[filterMode,setFilterMode]=useState<'any'|'all'>('any');return <main className="cvp-input-doc cvp-button-doc cvp-text-doc">
 <header className="cvp-input-doc__hero"><div><span>Component 10 · Standardized</span><h1>Text Button</h1></div><div><p>The quietest CVP action family for utility, disclosure, inline context, and navigation—with explicit semantic variants.</p><span className="cvp-input-doc__status">Ready for implementation</span></div></header>
 <section className="cvp-input-doc__panel"><header><b>01</b><div><h2>Anatomy and semantics</h2><p>Renders a native button for actions or an anchor for navigation; disabled links lose their destination.</p></div></header><div className="cvp-input-doc__anatomy"><div className="cvp-input-doc__live cvp-button-doc__live"><TextButton>Clear filters</TextButton></div><ol><li><b>1</b><span><strong>Element</strong> Choose button for actions and anchor for destinations.</span></li><li><b>2</b><span><strong>Label</strong> Concise visible action or destination name.</span></li><li><b>3</b><span><strong>Optional icon</strong> Decorative reinforcement for nav and disclosure.</span></li></ol></div></section>
 <section className="cvp-input-doc__panel"><header><b>02</b><div><h2>Complete state model</h2><p>Default state behavior is shared by every semantic variant.</p></div></header><div className="cvp-button-doc__states">{states.map(([label,state,disabled,loading])=><article key={label}><span>{label}</span><TextButton disabled={disabled} loading={loading} data-preview-state={state}>Clear filters</TextButton></article>)}</div></section>
 <section className="cvp-input-doc__panel"><header><b>03</b><div><h2>Semantic variants</h2><p>Variants represent different jobs—not cosmetic alternatives.</p></div></header><div className="cvp-text-doc__variants"><article><span>Default · utility</span><TextButton>View details</TextButton></article><article><span>Secondary · neutral</span><TextButton variant="secondary">Import content</TextButton></article><article><span>Toggle · disclosure</span><TextButton variant="toggle" active={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Hide':'Show'} {expanded?<ChevronUp size={14}/>:<ChevronDown size={14}/>}</TextButton></article><article><span>Minimal · inline</span><TextButton variant="minimal" active={filterMode==='all'} onClick={()=>setFilterMode(v=>v==='any'?'all':'any')}>{filterMode==='any'?'any filter':'all filters'}</TextButton></article><article><span>Minimal inverted</span><TextButton variant="minimal-inverted">Clear</TextButton></article><article><span>Nav · current page hover</span><TextButton href="#text-button-nav" variant="nav" active data-preview-state="hover" icon={<Grid/>}>Overview</TextButton></article><article><span>Nav · destination</span><TextButton href="#text-button-files" variant="nav" icon={<FileText/>}>Files</TextButton></article><article><span>Disabled link</span><TextButton href="#unavailable" variant="nav" disabled>Unavailable</TextButton></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>04</b><div><h2>Theme parity</h2><p>Every label, surface, focus, and navigation role resolves locally in both themes.</p></div></header><div className="cvp-input-doc__themes"><article data-theme="dark"><span>Dark</span><TextButton variant="secondary">View options</TextButton></article><article data-theme="light"><span>Light</span><TextButton variant="secondary">View options</TextButton></article></div></section>
 <section className="cvp-input-doc__panel"><header><b>05</b><div><h2>Token contract</h2><p>Variants consume registered Tier 3 text-button roles rather than class-local values.</p></div></header><ComponentTokenContract label="Text Button token contract" rows={rows}/></section>
 <section className="cvp-input-doc__grid"><article className="cvp-input-doc__panel"><header><b>06</b><div><h2>Accessibility contract</h2></div></header><ul><li>Use buttons for actions and anchors for navigation.</li><li>Toggle exposes <code>aria-pressed</code>; nav active exposes <code>aria-current</code>.</li><li>Disabled links remove <code>href</code> and keyboard focus.</li><li>Focus remains independently visible.</li><li>Loading exposes busy state and blocks repeat activation.</li></ul></article><article className="cvp-input-doc__panel"><header><b>07</b><div><h2>Usage decisions</h2></div></header><ul><li>Default: quiet utility action.</li><li>Secondary: neutral action with hover surface.</li><li>Toggle: disclosure or binary display preference.</li><li>Minimal: inline grammatical or filter context.</li><li>Nav: destination with optional leading icon; current-page hover uses the compact disabled-link treatment.</li></ul></article></section>
 <footer className="cvp-input-doc__footer"><span>CVP text action reference</span><p>Button or link · Six semantic variants · Loading · Themes</p></footer>
</main>}
